import vueStrToReactStr from "./src/vueStrToReactStr";
import { readdir, readFile, writeFile } from "node:fs/promises";

(async () => {
  let mdLines = [
    "# Examples",
    "File auto-generated by [generateExamples.ts](./generateExamples.ts)",
  ];

  for (const vueName of (await readdir("./fixtures")).filter((n) =>
    n.endsWith(".vue")
  )) {
    const name = vueName.replace(/\.vue$/, "");
    const vueCode = await readFile(`./fixtures/${vueName}`, "utf8");
    const reactCode = vueStrToReactStr(vueCode);

    mdLines.push(
      `## ${name}`,
      "```vue",
      vueCode,
      "```",
      "```tsx",
      reactCode,
      "```"
    );
  }

  writeFile("./examples.md", mdLines.join("\n"));
})();
